name: check_query_identifiers.yaml
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format_check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.9"

    runs-on: ${{ matrix.os }}

    name: Run Check Query Identifiers

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv venv
          uv pip install -r requirements.txt

      - name: Activate virtualenv
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Run Python script
        run: python src/scribe_data/check/check_query_identifiers.py
